---

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Get NetworkDevices
    dna_networkdevice:
      dna_url: '{{ dnaurl }}'
      dna_username: '{{ dnauser }}'
      dna_password: '{{ dnapass }}'
      validate_certs: False
      api_endpoint: '/serial-number/FXS1932Q1SE'
    register: networkdevice_facts

  - debug:
      var: networkdevice_facts
